# To make the Git commit signing work.
# Withtout it, Git complains that:
# error: gpg failed to sign the data
# [...]
# [GNUPG:] PINENTRY_LAUNCHED 988674 tty 1.1.1 not a tty tmux-256color :1 ? 1000/1000 -
# [...]
# export GPG_TTY=$TTY
# export GPG_TTY=$(tty)

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"
# Number of lines loaded in memory
export HISTSIZE=1000000000
# Number of lines saved in ~/.zsh_history
export SAVEHIST=100000000

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(command-not-found git gitfast bundler docker sudo rbenv docker-compose golang colored-man-pages dirhistory vagrant zsh-autosuggestions)

# User configuration

source $ZSH/oh-my-zsh.sh

# This is specific to the 'agnoster' theme.
# Remove ${USER}@$(hostname) from the prompt.
prompt_context() {
  # Customize this part of the front with information from:
  # https://github.com/agnoster/agnoster-zsh-theme/issues/39#issuecomment-307338817
  prompt_segment $CURRENT_FG default  "🌈"
}

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export SVN_EDITOR=vim
export EDITOR=vim
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

source ~/.zsh/init/env
source ~/.zsh/init/alias

[[ -f ~/.bin/tmuxinator.zsh ]] && source ~/.bin/tmuxinator.zsh

# Auto completions
source ~/.zsh/init/autocomplete

# Modify ZLE widget key binding (cf. man zshzle)
bindkey ^W forward-word

source ~/.zsh/init/startup
source ~/.zsh/init/functions

# >>>> Vagrant command completion (start)
fpath=(/opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/contrib/zsh $fpath)
compinit
# <<<<  Vagrant command completion (end)

export SSH_AGENT_PID=""
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# Added by `rbenv init` on mar. 17 sept. 2024 09:03:43 CEST
eval "$(rbenv init - --no-rehash zsh)"
